image: rocker/geospatial:4.4.3

stages:
  - test

testing:
    stage: test
    script:
        - R -e "remotes::install_deps(dependencies='hard', upgrade=FALSE, repos=c(Sys.getenv('CRAN_URL'), 'https://packagemanager.rstudio.com/cran/latest', 'https://cran.curtin.edu.au'))"
        - R -e 'devtools::check()'
        - Rscript -e 'devtools::test()'
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == 'main'

