name: malariaAtlas
channels:
  - conda-forge
  - defaults
dependencies:
  - r-stringi=1.7.3
  - r-curl=4.3.2
  - r-sp=1.4_5
  - r-rgdal=1.5_23
  - r-dplyr=1.0.4
  - r-gridextra=2.3
  - r-testthat=3.0.1
  - r-base=4.0.3
  - r-httr=1.4.2
  - r-xml2=1.3.2
  - r-tidyr=1.1.2
  - r-devtools=2.3.2
  - r-ggplot2=3.3.3
  - r-raster=3.4_5
  - r-rmarkdown=2.6

